export const FETCH_PRODUCT_INFO = 'overview/FETCH_PRODUCT_INFO';
export const FETCH_PRODUCT_LIST = 'overview/FETCH_PRODUCT_LIST';
export const FETCH_PRODUCT_STYLES = 'overview/FETCH_PRODUCT_STYLES';
export const FETCH_PRODUCT_INFO_SUCCESS = 'overview/FETCH_PRODUCT_INFO_SUCCESS';
export const FETCH_PRODUCT_LIST_SUCCESS = 'overview/FETCH_PRODUCT_LIST_SUCCESS';
export const FETCH_PRODUCT_STYLES_SUCCESS =
  'overview/FETCH_PRODUCT_STYLES_SUCCESS';
export const FETCH_PRODUCT_INFO_FAIL = 'overview/FETCH_PRODUCT_INFO_FAIL';
export const FETCH_PRODUCT_LIST_FAIL = 'overview/FETCH_PRODUCT_LIST_FAIL';
export const FETCH_PRODUCT_STYLES_FAIL = 'overview/FETCH_PRODUCT_STYLES_FAIL';
